### ISSUE TITLE
Windows transcode server possible?

### ISSUE THREAD

**Issue by merc4derp** [joshuaboniface/rffmpeg#17]
For AMD gpus currently AMF is working much better than VAAPI and AMF in amdgpu-pro is a mess.

What would be needed to offload the transcodes with rffmpeg to a windows machine? Please don't say WSL2. That's also a mess for gpu acceleration.

**Comment by joshuaboniface** [comment]
To be completely honest, I don't use Windows at all so I'm not sure. At the very least, you'd need an SSH server so that the media server can SSH to the Windows box. Beyond that, you'd need some sort of shared filesystem (I use NFS in my example but theoretically SMB would work too, I've just never tested it), and some of the paths might be wonky, but pretty much this is just a wrapper around a command that looks like `ssh user@host /path/to/ffmpeg <all the args I was passed>`, so I imagine it would be somewhat compatible.

**Comment by c89williams** [comment]
I got remote NVENC transcoding working with a Debian source and a Windows 10 target with minimal effort. Used the OpenSSH Server bundled with Windows, and the custom Jellyfin ffmpeg binaries (did not try others) plus a modification to rffmpeg to replace linux paths with Windows-friendly ones. Works very smoothly with no apparent issues.

**Comment by Dominaezzz** [comment]
I got it to work on Windows as well but using the docker-mod. I wrote a wrapper script on the Windows side to convert the paths.

**Comment by Xaque8787** [comment]
> I got it to work on Windows as well but using the docker-mod. I wrote a wrapper script on the Windows side to convert the paths.

Could you perhaps share what you did. I could use some insight when getting it working on the Windows side of things.

**Comment by Dominaezzz** [comment]
Sure, when I get some time I'll write something up.

**Comment by Dominaezzz** [comment]
https://gist.github.com/Dominaezzz/1b8e35e987f2f078c50c9a609908594e

It's not a step by step guide but difficult bits are covered.

**Comment by mat926** [comment]
Is there a docker for the transcode server?

**Comment by oddmaniv** [comment]
Very late to the party - but I got this working with HWA in WSL2 on my gaming machine!
NVENC is supported within WSL2 now. Follow the setup guide and you should be fine. 

You need to add the nvidia encode libs to your PATH if you want to use HWA. Add this line to your `~/.bashrc`

`export PATH="$PATH:/user/lib/wsl/lib`

Don't install any nvidia drivers etc within WSL2, just make sure your windows machine has the latest driver for you GPU. And use the jellyfin ffmpeg binaries.
