### ISSUE TITLE
Does FFMPEG support multi CPU sockets?

### ISSUE THREAD

**Issue by BastionNtB** [joshuaboniface/rffmpeg#18]
Hello! Just found this awesome repository, looks awesome. I'm going to be setting it up. I'm just wondering if it can take advantage of a multi-CPU server, say, a server with 4 physical CPUs as an example.

If not already natively supported, I could see something where you could have a setting specified the number of instances of ffmpeg would correspond to the amount of CPUs. So if rffmpeg sends off 2 different encoding/transcoding jobs the first one would open up on CPU 0, and the next on CPU 1. Just an idea.

Not sure if it's even possible. But I at least wanted to tell you how awesome I think this idea is and it will definitely be coming in handy!

**Comment by joshuaboniface** [comment]
Not explicitly, no, but implicitly it would if there are multiple simultaneous ffmpeg processes on the host. The OS scheduler would handle that however it handles that.

Doing so explicitly though would involve argument mangling (same as hardware acceleration) which is something I don't really want rffmpeg to get into since it's one heck of can of worms.

**Comment by BastionNtB** [comment]
Gotcha, thanks for the detailed response! Awesome work! :)
