### ISSUE TITLE
Kubernetes and Docker and CephFS

### ISSUE THREAD

**Issue by voarsh2** [joshuaboniface/rffmpeg#29]
Hi.

Briefly looked at this repo as I have 5 servers but no GPU's.
I am running Jellyfin in a docker container on Kubernetes and saw this doesn't have docker support and relies on ssh?
Within Kubernetes, SSH into a pod is not really going to work well, I've seen some examples of a rsync server/client docker image, but I've not much experience with it. For example it can generate a fixed SSH key, but you'd need to use statefulset deployment or get a fixed ClusterIP for SSH to work.

Since this project is targeted at non-Docker installs, I am not sure I could adopt it - it's a neat idea - and painfully needed if you don't want to buy lots of beefy CPU's or GPU's.

TL:DL:
Seems no Docker support, saw this: https://github.com/BasixKOR/rffmpeg-docker
SSH into Kubernetes Docker container... is probably not an easy/good idea.
Reading media and storing the transcodes in a SHARED filesystem that all Docker pods can access at the same time (think NFS), removing SSH part by accessing a shared transcode directory would help in my case specifically.

**Comment by joshuaboniface** [comment]
I'm not really sure what you're suggesting or reporting. Fundamentally, rffmpeg is built for a particular usecase - it is really just a glorified `ssh` wrapper script - and unfortunately due to its design, Kubernetes is not a good fit for that usecase (as you and others have pointed out). It's not a distributed ffmpeg load sharding tool that can run statelessly; writing such a thing is way beyond my skillset. That's fine, it just means it's not the tool for you.
