### ISSUE TITLE
ssh pass auth

### ISSUE THREAD

**Issue by KRDucky** [joshuaboniface/rffmpeg#30]
How can we use ssh password auth on here? I am running solely on my LAN so really dont want to use ssh keys if I can help it especially since I tried the key method and it doesnt work. It still asks for the transcode server password. I setup the key to not ask for a password. 
I am running linuxserver jellyfin on my server and stock ubuntu on the transcode box. 
Or how can we use sshpass with this?

**Comment by Sim0nW0lf** [comment]
Maybe you could add both commands, sshpass and ssh here instead of only ssh. https://github.com/joshuaboniface/rffmpeg/blob/883d4333685af606af1685264f1b481fc2635951/rffmpeg.yml.sample#L55-L57
But honestly I don't think it's a good idea at all. SSH keys work fine in any setup. You just have to configure them correctly once and there are so many awesome tutorials to set them up.

**Comment by joshuaboniface** [comment]
Pretty much exactly what Sim0nW0lf says. You can replace the SSH binary with anything you want, but honestly use SSH keys, it's why it's designed that way.
