### ISSUE TITLE
Logging enhancement request

### ISSUE THREAD

**Issue by gitdeath** [joshuaboniface/rffmpeg#42]
Problem Statement: The logfile name is pulled from the .yml file, but I can't figure out a way to append a variable date to the name of the log by changing the yml. 

Request: Have the application pull the name, exactly as it is today from the yml, except as it goes to write append a date.

Reason: 
I'm interested in taking advantage of Jellyfin's log maintenance, by storing the log file in the Jellyfin log directory, but the current implementation never 'rolls', so it just continues to grow.

**Comment by joshuaboniface** [comment]
This isn't currently supported since I use `logrotate` for this, but I'd be open to a clean implementation PR'd against the project if/when you get it working.

To get started, the logfile name config is imported at line 110 of the `rffmpeg` tool:

```
config["logfile"] = config_logging.get("logfile", "/var/log/jellyfin/rffmpeg.log")
```

You could easily append a date here like:

```
config["logfile"] = config_logging.get("logfile", "/var/log/jellyfin/rffmpeg.log") + "_" + datetime.now()
```

...or such, adjusting the string value to whatever format you'd prefer. This configuration - as well as opening/writing the logfile - is done at each script invocation, i.e. whenever something starts playing with `rffmpeg`, so it's quite flexible in that regard.

For a proper implementation, I would require it to be behind a config flag (e.g. `logfile_append_date` or such), wiht a default value of `False`, and only append it when the flag is active.

**Comment by pyaniz** [comment]
I can get this working pretty quickly - Can you add me as contributor to the project? I'll branch it and create a pull request for you to review.
Agreed on the flag as well.

**Comment by gitdeath** [comment]
the enhancement looks great! thank you both! I've updated my rffmpeg.yml to add the parameters and will go live the moment it is fully approved here.

@pyaniz
@joshuaboniface

**Comment by gitdeath** [comment]
Seems to crash on an init.. was able to reach out to pyaniz and test.

**Comment by pyaniz** [comment]
The suggested way for this variable using the function handle seems to be the culprit (I am unsure of why)
` config["logfile"] = f"{config['datedlogdir']}/{datetime.today().strftime('%Y%m%d')}_rffmpeg.log"`
I changed it for 
`        config["logfile"] = config['datedlogdir'] + "/" + datetime.today().strftime('%Y%m%d') + "_rffmpeg.log"`
We tested building the container and it works well. Will submit a new pull request.
