### ISSUE TITLE
Dynamically Add/Remove Hosts

### ISSUE THREAD

**Issue by obsidiangroup** [joshuaboniface/rffmpeg#5]
Is there a way to dynamically add / remove a node from the cluster -- or any way to add / remove a node from the cluster other than editing the rffmpeg.yml file?

**Comment by joshuaboniface** [comment]
Right now no; there is no actice running process and rffmpeg reads the yaml each time it runs to determine the hosts.

I'm considering this as a future feature once I expand rffmpeg, but for now editing the yaml (which can be done programmatically) is the only way.

**Comment by joshuaboniface** [comment]
I've continued to think about this feature request, and for now I'd prefer to keep rffmpeg as a "run and done" program, without keeping external state anywhere except its runtime files.

To reiterate a side-point I made above, it is very easy to edit `rffmpeg.yml` programmatically. For instance using the PyYAML library (just like the script itself does) to read in the YAML config, update the host list, and write it back out. I don't think there's any value in adding this sort of thing to rffmpeg *itself*, since that would be a catch-22, but an external script could easily be written to add/remove hosts based on pretty much any condition you would want. Failed host detection within rffmpeg also takes care of situations where a host is down, and it will be ignored for the duration of the transcoding session, and by any other instances that start while the initial one is still running.
