### ISSUE TITLE
Add weights to servers

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [joshuaboniface/rffmpeg#8]
Would be nice if we could add weights and/or parameters to servers, like for instance 1 server that can handle 2 1080p streams alongside another server that can run 2 4k streams, as well as setting CPU and other settings independently per host (nvenc on one, vaapi on another, 4 threads vs 12, etc)

Not at all mandatory, but still a neat idea and would make this a lot more useful in my application.

**Comment by joshuaboniface** [comment]
The first aspect, weighting servers (so for every 2 on one it sends 1 to the other) is definitely doable and a very good idea.

The second aspect isn't possible, since `rffmpeg` just wraps whatever options are sent to it from the calling environment, and adjusting options in-flight is an abyss I don't want this tool to stare into.
